# Generated by Django 5.2.6 on 2025-10-31 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='noticias_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
