# Generated by Django 5.2.6 on 2025-11-12 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_noticia_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='usuarios_que_visitaram',
            field=models.ManyToManyField(blank=True, related_name='noticias_visualizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
