# Generated by Django 5.2.6 on 2025-12-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_noticia_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoResumo', models.TextField()),
                ('noticiaRelacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.noticia')),
            ],
        ),
    ]
