# Generated by Django 5.2.6 on 2025-12-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
