# Generated by Django 5.2.6 on 2025-12-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_noticia_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='prompt',
        ),
    ]
